-- MySQL Script generated by MySQL Workbench
-- Sat Jul 21 20:27:36 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ginpay
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ginpay
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ginpay` DEFAULT CHARACTER SET utf8 ;
USE `ginpay` ;

-- -----------------------------------------------------
-- Table `ginpay`.`chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ginpay`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ginpay`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ginpay`.`user` (
  `id` VARCHAR(91) NOT NULL,
  `point` DOUBLE NULL DEFAULT 0,
  `image` TEXT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ginpay`.`destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ginpay`.`destination` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `image` TEXT NULL,
  `point` DOUBLE NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ginpay`.`user_travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ginpay`.`user_travel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(91) NOT NULL,
  `destination_id` INT NOT NULL,
  `message` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_travel_user_idx` (`user_id` ASC),
  INDEX `fk_user_travel_destination_idx` (`destination_id` ASC)
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ginpay`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ginpay`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `recommender_id` INT NULL,
  `user_id` VARCHAR(91) NOT NULL,
  `destination_id` INT NOT NULL,
  `evaluationcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evaluation_user_idx` (`user_id` ASC),
  INDEX `fk_evaluation_destination_idx` (`destination_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
