INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (1, 'Hokkaido', 'https://search.find47.jp/ja/i/x1QYd/image_file?type=detail_thumb', 0.07, 'Hokkaido (北海道, Hokkaidō) is the second largest, northernmost and least developed of Japan''s four main islands. Its weather is harsh in winter with lots of snowfall, below zero temperatures and frozen seas, while in summer it does not get as hot and humid as in the other parts of the country.

With its unspoiled nature, Hokkaido attracts many outdoor lovers, including skiers and snowboarders in the colder seasons and hikers, cyclists and campers from June to September.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (2, 'Aomori', 'https://search.find47.jp/ja/i/05Rw2/image_file?type=detail_thumb', 0.35, 'Aomori City (青森) in Aomori Prefecture is the northernmost prefectural capital city on Honshu, Japan''s main island. This port town used to be the main departure point to Hokkaido via ferry; and, although it remains the main port for car ferries, the opening of the Seikan Undersea Railway Tunnel and the advent of cheap flights have reduced ridership and many travelers now bypass the city altogether. Today Aomori is best known for its spectacular Nebuta Matsuri summer festival.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (3, 'Iwate', 'https://search.find47.jp/ja/i/Xvpfi/image_file?type=detail_thumb', 0.44, 'The Tohoku Region (東北地方, Tōhoku Chihō, literally "North East Region") consists of six prefectures in the north of Japan''s largest island, Honshu. It is well known for its countryside, mountains, lakes, hot springs, high quality rice and rough winters.

The Tohoku Region was hit by the earthquake and tsunami of March 11, 2011 and the ensuing nuclear accident. However, most areas of the Tohoku Region are now safe and welcoming tourists again. Of all the destinations in our travel guide, only Sendai, Matsushima, Iwaki and the Sanriku Coast suffered direct damage from the earthquake and tsunami, and even there most attractions reopened within a few weeks or months.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (4, 'Miyagi', 'https://search.find47.jp/ja/i/gBvVl/image_file?type=detail_thumb', 0.27, 'The Tohoku Region (東北地方, Tōhoku Chihō, literally "North East Region") consists of six prefectures in the north of Japan''s largest island, Honshu. It is well known for its countryside, mountains, lakes, hot springs, high quality rice and rough winters.

The Tohoku Region was hit by the earthquake and tsunami of March 11, 2011 and the ensuing nuclear accident. However, most areas of the Tohoku Region are now safe and welcoming tourists again. Of all the destinations in our travel guide, only Sendai, Matsushima, Iwaki and the Sanriku Coast suffered direct damage from the earthquake and tsunami, and even there most attractions reopened within a few weeks or months.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (5, 'Akita', 'https://search.find47.jp/ja/i/ra1fv/image_file?type=detail_thumb', 0.4, 'The Tohoku Region (東北地方, Tōhoku Chihō, literally "North East Region") consists of six prefectures in the north of Japan''s largest island, Honshu. It is well known for its countryside, mountains, lakes, hot springs, high quality rice and rough winters.

The Tohoku Region was hit by the earthquake and tsunami of March 11, 2011 and the ensuing nuclear accident. However, most areas of the Tohoku Region are now safe and welcoming tourists again. Of all the destinations in our travel guide, only Sendai, Matsushima, Iwaki and the Sanriku Coast suffered direct damage from the earthquake and tsunami, and even there most attractions reopened within a few weeks or months.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (6, 'Yamagata', 'https://search.find47.jp/ja/i/eOHgQ/image_file?type=detail_thumb', 0.38, 'The Tohoku Region (東北地方, Tōhoku Chihō, literally "North East Region") consists of six prefectures in the north of Japan''s largest island, Honshu. It is well known for its countryside, mountains, lakes, hot springs, high quality rice and rough winters.

The Tohoku Region was hit by the earthquake and tsunami of March 11, 2011 and the ensuing nuclear accident. However, most areas of the Tohoku Region are now safe and welcoming tourists again. Of all the destinations in our travel guide, only Sendai, Matsushima, Iwaki and the Sanriku Coast suffered direct damage from the earthquake and tsunami, and even there most attractions reopened within a few weeks or months.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (7, 'Fukushima', 'https://search.find47.jp/ja/i/nBjni/image_file?type=detail_thumb', 0.41, 'The Tohoku Region (東北地方, Tōhoku Chihō, literally "North East Region") consists of six prefectures in the north of Japan''s largest island, Honshu. It is well known for its countryside, mountains, lakes, hot springs, high quality rice and rough winters.

The Tohoku Region was hit by the earthquake and tsunami of March 11, 2011 and the ensuing nuclear accident. However, most areas of the Tohoku Region are now safe and welcoming tourists again. Of all the destinations in our travel guide, only Sendai, Matsushima, Iwaki and the Sanriku Coast suffered direct damage from the earthquake and tsunami, and even there most attractions reopened within a few weeks or months.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (8, 'Ibaraki', 'https://search.find47.jp/ja/i/Ocmrd/image_file?type=detail_thumb', 0.29, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (9, 'Tochigi', 'https://search.find47.jp/ja/i/JQ4c5/image_file?type=detail_thumb', 0.21, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (10, 'Gunma', 'https://search.find47.jp/ja/i/MIFrW/image_file?type=detail_thumb', 0.36, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (11, 'Saitama', 'https://search.find47.jp/ja/i/s4DeO/image_file?type=detail_thumb', 0.23, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (12, 'Chiba', 'https://search.find47.jp/ja/i/Dhnyk/image_file?type=detail_thumb', 0.03, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (13, 'Tokyo', 'https://search.find47.jp/ja/i/E7TS9/image_file?type=detail_thumb', 0.01, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (14, 'Kanagawa', 'https://search.find47.jp/ja/i/fsexT/image_file?type=detail_thumb', 0.06, 'The Kanto (関東, Kantō, literally "east of the border") is Japan''s largest plain and very densely populated. The large metropolises of Tokyo and Yokohama are located in the Kanto Region which consists of seven prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (15, 'Niigata', 'https://search.find47.jp/ja/i/Q7Dvg/image_file?type=detail_thumb', 0.3, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (16, 'Toyama', 'https://search.find47.jp/ja/i/s7hA0/image_file?type=detail_thumb', 0.25, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (17, 'Ishikawa', 'https://search.find47.jp/ja/i/MSwaP/image_file?type=detail_thumb', 0.19, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (18, 'Fukui', 'https://search.find47.jp/ja/i/2rsay/image_file?type=detail_thumb', 0.45, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (19, 'Yamanashi', 'https://search.find47.jp/ja/i/aRrGT/image_file?type=detail_thumb', 0.13, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (20, 'Nagano', 'https://search.find47.jp/ja/i/2Tpoe/image_file?type=detail_thumb', 0.16, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (21, 'Gifu', 'https://search.find47.jp/ja/i/ORpvF/image_file?type=detail_thumb', 0.18, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (22, 'Shizuoka', 'https://search.find47.jp/ja/i/MPFYH/image_file?type=detail_thumb', 0.14, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (23, 'Aichi', 'https://search.find47.jp/ja/i/sESC5/image_file?type=detail_thumb', 0.09, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (24, 'Mie', 'https://search.find47.jp/ja/i/X2lVN/image_file?type=detail_thumb', 0.34, 'The Chubu Region (中部地方, Chūbu Chihō, literally "central part") consists of nine prefectures and is located in the center of Japan''s largest island Honshu.

The northern part of the Chubu Region along the Sea of Japan coast (Fukui, Ishikawa, Toyama) is also known as Hokuriku Region, while the southern part (Shizuoka, Aichi, Gifu) is also known as Tokai Region and the prefectures of Yamanashi, Nagano and Niigata as the Koshinetsu Region.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (25, 'Shiga', 'https://search.find47.jp/ja/i/bXHLS/image_file?type=detail_thumb', 0.33, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (26, 'Kyoto', 'https://search.find47.jp/ja/i/y3sfJ/image_file?type=detail_thumb', 0.04, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (27, 'Osaka', 'https://search.find47.jp/ja/i/5AU8m/image_file?type=detail_thumb', 0.02, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (28, 'Hyogo', 'https://search.find47.jp/ja/i/Kjy4h/image_file?type=detail_thumb', 0.11, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (29, 'Nara', 'https://search.find47.jp/ja/i/BAAjp/image_file?type=detail_thumb', 0.1, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (30, 'Wakayama', 'https://search.find47.jp/ja/i/ggZyM/image_file?type=detail_thumb', 0.24, 'The Kinki Region (近畿地方, Kinki Chihō), also commonly known as Kansai (関西, literally "west of the border") encompasses the Kinki Plain and consists of seven prefectures. It used to be the political and cultural center of Japan for many centuries and includes the cities of Kyoto, Osaka, Nara and Kobe.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (31, 'Tottori', 'https://search.find47.jp/ja/i/CLkNL/image_file?type=detail_thumb', 0.43, 'The Chugoku Region (中国地方, Chūgoku Chihō, literally "central country") makes up the western part of Japan''s main island Honshu. It is commonly subdivided into the heavily urbanized and industrialized Sanyo Region along the Seto Inland Sea coast and the much more rural Sanin Region along the Sea of Japan coast.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (32, 'Shimane', 'https://search.find47.jp/ja/i/bzCwS/image_file?type=detail_thumb', 0.47, 'The Chugoku Region (中国地方, Chūgoku Chihō, literally "central country") makes up the western part of Japan''s main island Honshu. It is commonly subdivided into the heavily urbanized and industrialized Sanyo Region along the Seto Inland Sea coast and the much more rural Sanin Region along the Sea of Japan coast.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (33, 'Okayama', 'https://search.find47.jp/ja/i/PN3vO/image_file?type=detail_thumb', 0.32, 'The Chugoku Region (中国地方, Chūgoku Chihō, literally "central country") makes up the western part of Japan''s main island Honshu. It is commonly subdivided into the heavily urbanized and industrialized Sanyo Region along the Seto Inland Sea coast and the much more rural Sanin Region along the Sea of Japan coast.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (34, 'Hiroshima', 'https://search.find47.jp/ja/i/JIjFm/image_file?type=detail_thumb', 0.15, 'The Chugoku Region (中国地方, Chūgoku Chihō, literally "central country") makes up the western part of Japan''s main island Honshu. It is commonly subdivided into the heavily urbanized and industrialized Sanyo Region along the Seto Inland Sea coast and the much more rural Sanin Region along the Sea of Japan coast.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (35, 'Yamaguchi', 'https://search.find47.jp/ja/i/dJwzy/image_file?type=detail_thumb', 0.22, 'The Chugoku Region (中国地方, Chūgoku Chihō, literally "central country") makes up the western part of Japan''s main island Honshu. It is commonly subdivided into the heavily urbanized and industrialized Sanyo Region along the Seto Inland Sea coast and the much more rural Sanin Region along the Sea of Japan coast.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (36, 'Tokushima', 'https://search.find47.jp/ja/i/JQkmW/image_file?type=detail_thumb', 0.42, 'Shikoku (四国, literally "four countries") is Japan''s fourth largest island, southwest of Japan''s main island Honshu. True to its name, Shikoku is divided into four prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (37, 'Kagawa', 'https://search.find47.jp/ja/i/Y7I3H/image_file?type=detail_thumb', 0.28, 'Shikoku (四国, literally "four countries") is Japan''s fourth largest island, southwest of Japan''s main island Honshu. True to its name, Shikoku is divided into four prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (38, 'Ehime', 'https://search.find47.jp/ja/i/MOHWD/image_file?type=detail_thumb', 0.37, 'Shikoku (四国, literally "four countries") is Japan''s fourth largest island, southwest of Japan''s main island Honshu. True to its name, Shikoku is divided into four prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (39, 'Kochi', 'https://search.find47.jp/ja/i/b0Rj8/image_file?type=detail_thumb', 0.46, 'Shikoku (四国, literally "four countries") is Japan''s fourth largest island, southwest of Japan''s main island Honshu. True to its name, Shikoku is divided into four prefectures.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (40, 'Fukuoka', 'https://search.find47.jp/ja/i/JSwdQ/image_file?type=detail_thumb', 0.05, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (41, 'Saga', 'https://search.find47.jp/ja/i/PGz9b/image_file?type=detail_thumb', 0.31, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (42, 'Nagasaki', 'https://search.find47.jp/ja/i/ebSMz/image_file?type=detail_thumb', 0.17, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (43, 'Kumamoto', 'https://search.find47.jp/ja/i/jTnwz/image_file?type=detail_thumb', 0.2, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (44, 'Oita', 'https://search.find47.jp/ja/i/Vr5ws/image_file?type=detail_thumb', 0.12, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (45, 'Miyazaki', 'https://search.find47.jp/ja/i/QHl4x/image_file?type=detail_thumb', 0.39, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (46, 'Kagoshima', 'https://search.find47.jp/ja/i/j49zC/image_file?type=detail_thumb', 0.26, 'Kyushu (九州, Kyūshū, literally "nine provinces") is Japan''s third largest island, located southwest of the main island Honshu. An early center of Japanese civilization, Kyushu offers many historic treasures, modern cities and natural beauty.');
INSERT INTO ginpay.destination (id, name, image, point, description) VALUES (47, 'Okinawa', 'https://search.find47.jp/ja/i/cQQMQ/image_file?type=detail_thumb', 0.08, 'Okinawa (沖縄県, Okinawa-ken) is Japan''s southernmost prefecture, consisting of a few dozen, small islands in the southern half of the Nansei Shoto, the island chain which stretches over about one thousand kilometers from Kyushu to Taiwan.

Okinawa Prefecture can be divided into three major island groups, the Okinawa Islands (Okinawa Shoto) around Okinawa Island (Okinawa Honto), the Miyako Islands (Miyako Retto) around Miyako Island and the Yaeyama Islands (Yaeyama Retto) around Ishigaki Island.');